### ISSUE TITLE
Very long parsing

### ISSUE THREAD

**Issue by pierrocknroll** [thinkwelltwd/device_detector#3]
Hello, and thank you for your great parser !

The only problem I'm facing is that the parsing is long, very much longer than other parsers like [woothee](https://github.com/woothee/woothee-python), [ua-parser](https://github.com/ua-parser/uap-python) or [httpagentparser](https://github.com/shon/httpagentparser), BUT your results are more accurate :)

For example, with a simple script who only parse 400 lines, ua-parser made it in 1.009 seconds, and device_detector 219s. 

Is there any reason ? Maybe can you look how they made it compared to you ?

Thanks a lot

**Comment by thinkwelltwd** [comment]
(This is why there's no pypi release yet :wink: ) 

Regex compilation isn't cached. I didn't decide whether to compile when loading from yaml, or to lazily compile & cache when first used. The lazy mode is better for short runs but will use more memory. It's implemented in commit 5afc3c47b. 

Secondly, it'll always be at least an order of magnitude slower than the libraries you mention because of the device model parsing, which the other libraries don't support. If you don't need device info, then those libraries are the way to go, and I'd have used one of those myself instead.

**Comment by pierrocknroll** [comment]
Wow, your last commit improves the performances a lot !!
Thanks for your answer
